name: Bug report
description: Use this template to report bugs. Please fill in all required fields.
title: '[BUG] '
labels:
- bug
body:
- type: input
  id: summary
  attributes:
    label: Short summary
    description: One-line summary of the problem
    placeholder: e.g. Crash when opening Workbench
  validations:
    required: true
- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: Select the platform/OS you are using (required)
    options:
    - macOS
    - Windows
    - Linux
  validations:
    required: true
- type: dropdown
  id: hardware
  attributes:
    label: Hardware
    description: Select the hardware used (required)
    options:
    - alpha
    - tau
    - pico
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: Select the earliest version you can reproduce the bug with (required)
    options:
    - 3.0.0-beta-1
    - 2.2.1-release
  validations:
    required: true
- type: dropdown
  id: component
  attributes:
    label: Component
    description: Select the component that is affected
    options:
    - EigenD
    - Workbench
    - Stage
    - Agent
    - Hardware
    - Setup
  validations:
    required: true
- type: dropdown
  id: agent
  attributes:
    label: Agent
    description: Only fill this if Component = Agent
    options:
    - ableton_push
    - ahdsr
    - alpha_manager
    - arranger
    - audio
    - audio_unit
    - blownstring
    - cello
    - clarinet
    - clicker
    - clip_manager
    - conductor
    - console_mixer
    - continuum
    - controller
    - convolver
    - cycler
    - delay
    - drummer
    - envelope
    - finger
    - gain
    - illuminator
    - keyboard
    - keyboard_controller
    - keygroup
    - labeler
    - ladder_filter
    - language
    - latch
    - livepad
    - metronome
    - midi_clock
    - midi_converter
    - midi_device
    - midi_input
    - midi_monitor
    - midi_output
    - midi_pgm_chooser
    - midi_processor
    - osc_output
    - orb
    - panner
    - panpipe
    - pico_manager
    - player
    - polyphonic_summer
    - ranger
    - recorder
    - rectangle_osc
    - rig
    - sampler
    - sawtooth_osc
    - scale_illuminator
    - scale_manager
    - scaler
    - scheduler
    - shaper
    - sine_osc
    - soundplane
    - stringer
    - strummer
    - summer
    - synth_filter
    - t3d_device
    - t3d_output
    - tabulator
    - talker
    - triangle_osc
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Steps to reproduce
    description: Describe the steps to reproduce, expected vs actual behaviour
    placeholder: e.g. Crash when opening Workbench. if beta did you test on release version?
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Logs / additional info
    description: Paste logs, error messages, or add any other relevant info
    placeholder: e.g. attach eigend.0.log, workbench.0.log - use tools, open library directory 
  validations:
    required: false
