
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

import glob
import os
import select_tools

from os.path import join,dirname

EnsureSConsVersion(4,5,0)

AddOption('--list-targets', dest='list_targets', action='store_true', help='List all available targets')

master_env = select_tools.select()
master_env.Initialise()

# Check if development environment exists (for testing)
venv_dev_path = os.path.join(Dir('#').abspath, '.venv_dev')
if not os.path.exists(venv_dev_path):
    print("")
    print("⚠️  Development environment not found")
    print("   Run 'make dev-setup' to create .venv_dev/ for testing")
    print("   (Build will continue, but you won't be able to run tests)")
    print("")

#CacheDir(master_env.cache_dir())
SConscriptChdir(0)
SConsignFile()

VariantDir(join(master_env.subst('$TMPDIR')),'.',duplicate=0)

Export(master_env=master_env)

# Collect all directories with SConscript for potential targets
sconscript_dirs = []
for root,dirs,files in os.walk('.'):
    if 'SConscript' in files:
        sconscript_dirs.append(root)

for root,dirs,files in os.walk('.'):
    if 'SConscript.first' in files:
        env=master_env.Clone()
        SConscript(join(master_env.subst('$TMPDIR'),root,'SConscript.first'))

for root,dirs,files in os.walk('.'):
    if 'SConscript' in files:
        env=master_env.Clone()
        SConscript(join(master_env.subst('$TMPDIR'),root,'SConscript'), exports='env')

master_env.Finalise()

if GetOption('list_targets'):
    print("Available targets:")
    targets = sorted(master_env.ans.keys())
    # Add SConscript directories as potential targets
    for d in sorted(sconscript_dirs):
        if d != '.':  # Skip root
            targets.append(d.lstrip('./'))
    targets = sorted(set(targets))  # Remove duplicates
    for t in targets:
        print(f"  {t}")
    Exit(0)

ctags=None
if master_env.Detect('ctags'): ctags='ctags'
if master_env.Detect('ctags-exuberant'): ctags='ctags-exuberant'
if master_env.Detect('exctags'): ctags='exctags'
if master_env.Detect('exuberant-ctags'): ctags='exuberant-ctags'

if ctags and os.getenv('PI_CTAGS'):
    srcfiles1 = list(map(dirname,glob.glob(join('*','SConscript'))))
    srcfiles2 = list(map(dirname,glob.glob(join('*','*','SConscript'))))
    tags = master_env.Command('#tags',[],ctags+' --langdef=pip --langmap=pip:.pip --extra=+fq --c-kinds=+pxvtmdc --recurse %s' % ' '.join(srcfiles1+srcfiles2))
    master_env.AlwaysBuild(tags)
    master_env.Alias('target-default',tags)

master_env.Default(master_env.Alias('target-default'))
