agents:
- ableton_push
- ahdsr
- alpha_manager
- arranger
- audio
- audio_unit
- blownstring
- cello
- clarinet
- clicker
- clip_manager
- conductor
- console_mixer
- continuum
- controller
- convolver
- cycler
- delay
- drummer
- envelope
- finger
- gain
- illuminator
- keyboard
- keyboard_controller
- keygroup
- labeler
- ladder_filter
- language
- latch
- livepad
- metronome
- midi_clock
- midi_converter
- midi_device
- midi_input
- midi_monitor
- midi_output
- midi_pgm_chooser
- midi_processor
- osc_output
- orb
- panner
- panpipe
- pico_manager
- player
- polyphonic_summer
- ranger
- recorder
- rectangle_osc
- rig
- sampler
- sawtooth_osc
- scale_illuminator
- scale_manager
- scaler
- scheduler
- shaper
- sine_osc
- soundplane
- stringer
- strummer
- summer
- synth_filter
- t3d_device
- t3d_output
- tabulator
- talker
- triangle_osc
